// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using micro_lotto.Data;

namespace micro_lotto.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("micro_lotto.Data.Entities.Bet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int");

                    b.Property<int>("FifthNumber")
                        .HasColumnName("fifth_number")
                        .HasColumnType("int");

                    b.Property<int>("FirstNumber")
                        .HasColumnName("first_number")
                        .HasColumnType("int");

                    b.Property<int>("FourthNumber")
                        .HasColumnName("fourth_number")
                        .HasColumnType("int");

                    b.Property<string>("ISOTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("iso_time")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("SecondNumber")
                        .HasColumnName("second_number")
                        .HasColumnType("int");

                    b.Property<int>("ThirdNumber")
                        .HasColumnName("third_number")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Bet");
                });

            modelBuilder.Entity("micro_lotto.Data.Entities.Draw", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int");

                    b.Property<int>("FifthNumber")
                        .HasColumnName("fifth_number")
                        .HasColumnType("int");

                    b.Property<int>("FirstNumber")
                        .HasColumnName("first_number")
                        .HasColumnType("int");

                    b.Property<int>("FourthNumber")
                        .HasColumnName("fourth_number")
                        .HasColumnType("int");

                    b.Property<string>("ISOTime")
                        .HasColumnName("iso_time")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("SecondNumber")
                        .HasColumnName("second_number")
                        .HasColumnType("int");

                    b.Property<int>("ThirdNumber")
                        .HasColumnName("third_number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Draw");
                });

            modelBuilder.Entity("micro_lotto.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int");

                    b.Property<float>("Balance")
                        .HasColumnName("balance")
                        .HasColumnType("float");

                    b.Property<string>("Username")
                        .HasColumnName("username")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 9001f,
                            Username = "Test User"
                        });
                });

            modelBuilder.Entity("micro_lotto.Data.Entities.Bet", b =>
                {
                    b.HasOne("micro_lotto.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
